# Kustomization for OpenShift Regional DR environment.
resources:
- ../base
  # Use masquerade network interface.
  # Use internal ceph cluster.
patches:
- patch: |-
    - op: add
      path: /spec/template/spec/domain/devices/interfaces/0/masquerade
      value: {}
  target:
    kind: VirtualMachine
    name: vm
- patch: |-
    - op: replace
      path: /spec/storage/storageClassName
      value: ocs-storagecluster-ceph-rbd-virtualization
  target:
    kind: DataVolume
    name: root-disk
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
