---
apiVersion: v1
kind: Service
metadata:
  name: nick-rhel9
  namespace: nick
  labels:
    app: nick
spec:
  type: NodePort
  selector:
    kubevirt.io/domain: nick-rhel9
  ports:
    - name: ssh
      port: 22
      protocol: TCP
      targetPort: 22
