resources:
- vm.yaml
- dv.yaml
secretGenerator:
- files:
  - test_rsa.pub
  name: my-public-key
generatorOptions:
  disableNameSuffixHash: true
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    appname: vm
